---
sudo: required

language: ruby

services:
  - docker

addons:
  apt:
    packages:
      - devscripts

env:
  - TEST_SUITE=centos
  - TEST_SUITE=ubuntu
  - TEST_SUITE=debian

script:
  - checkbashisms install.sh
  - bundle exec kitchen test $TEST_SUITE

notifications:
  email:
    on_success: never
    on_failure: always
